default: &default
  adapter: postgresql
  #encoding: unicode
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: <%= ENV.fetch("RAILS_DATABASE_TIMEOUT") { 5000 } %>
  username: postgres
  password: postgres
  host: localhost
  database: smart-factory_development

hpm_db: &hpm_db
    database: u787840538_hpm_producao
    username: u787840538_hpm_producao
    password: Acti1793*
    adapter: mysql2
    host: 185.211.7.22
    port: 3306
    replica: true

default:

development:
  <<: *hpm_db
  database: u787840538_hpm_producao

test:
  <<: *default
  database: smart-factory_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %> 